version: '3'
services:
  db:
    container_name: db
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db
  server:
    container_name: server
    build: ./server
    ports:
      - '5000:5000'
    depends_on:
      - db
  client:
    container_name: client
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
    # allow interactive mode
    stdin_open: true
    tty: true
    depends_on:
      - server
volumes:
  data: